spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:mysql://khayn.synology.me:5306/memobox?useUnicode=yes&characterEncoding=UTF-8
    username: failmaster
    password: crd123!
  #    url: jdbc:h2:file:C:\\Users\\WojtekM\\Repozytorium\\test-db
  #    url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #task:
  #  template:
  #    allowMultipleTasks: false